/*
 ============================================================================
 Name        : waterFlowSensor.h
 Author      : Mateusz Kaczmarczyk
 Version     :
 Description :
 ============================================================================
 */
#ifndef WATERFLOESENSOR_H
#define WATERFLOESENSOR_H
#include <avr/io.h>
#include <avr/interrupt.h>
#include "math.h"

/**
 * @brief: Definitions of values to set for wfStatus
 */
#define	WF_COUNT_RUNNING	(1 << 0)
#define	WF_COUNT_STARTED	(1 << 1)
#define	WF_COUNT_SUSPEND	(1 << 2)
#define	WF_COUNT_LAUNCH		(1 << 3)
#define	WF_CAPTURE_TIME		(1 << 4)

volatile static uint8_t wfStatus = 0;	//@brief: Defines water flow sensor working status with definitions above
volatile uint16_t wfCount;				//@brief: Count pulses generated by water flow sensor

/**
 * @brief:	Start and stop water flow sensor reading
 * @param:	Water flow measurement
 *			0: Disabled
 *			1: Enabled
 * @return:	None
 */
void wfSensToggle(uint8_t enable);

/**
 * @brief:	Measure water flow using data captured from timer and ISR
 * @param:	None
 * @return:	Water flow as centilitres per minute [cl/minute] (1[cl] = 0.01[l])
 */
uint16_t measureWF(void);

#endif
